/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClosedTrade {
  'id' : TradeId,
  'pnl' : number,
  'closeTimestamp' : Time,
  'pair' : string,
  'side' : TradeSide,
  'closePrice' : number,
  'entryPrice' : number,
  'openTimestamp' : Time,
  'lotSize' : number,
}
export interface Position {
  'id' : TradeId,
  'pair' : string,
  'side' : TradeSide,
  'entryPrice' : number,
  'openTimestamp' : Time,
  'lotSize' : number,
}
export type Time = bigint;
export type TradeId = bigint;
export type TradeSide = { 'buy' : null } |
  { 'sell' : null };
export interface Transaction {
  'id' : TransactionId,
  'transactionType' : TransactionType,
  'timestamp' : Time,
  'amount' : number,
}
export type TransactionId = bigint;
export type TransactionType = { 'withdraw' : null } |
  { 'deposit' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'closeTrade' : ActorMethod<[TradeId, number], undefined>,
  'deposit' : ActorMethod<[number], undefined>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClosedTrades' : ActorMethod<[], Array<ClosedTrade>>,
  'getOpenPositions' : ActorMethod<[], Array<Position>>,
  'getTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeTrade' : ActorMethod<[string, TradeSide, number, number], TradeId>,
  'resetAccount' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'withdraw' : ActorMethod<[number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];