/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TradeId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const ClosedTrade = IDL.Record({
  'id' : TradeId,
  'pnl' : IDL.Float64,
  'closeTimestamp' : Time,
  'pair' : IDL.Text,
  'side' : TradeSide,
  'closePrice' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'openTimestamp' : Time,
  'lotSize' : IDL.Float64,
});
export const Position = IDL.Record({
  'id' : TradeId,
  'pair' : IDL.Text,
  'side' : TradeSide,
  'entryPrice' : IDL.Float64,
  'openTimestamp' : Time,
  'lotSize' : IDL.Float64,
});
export const TransactionId = IDL.Nat;
export const TransactionType = IDL.Variant({
  'withdraw' : IDL.Null,
  'deposit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : TransactionId,
  'transactionType' : TransactionType,
  'timestamp' : Time,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'closeTrade' : IDL.Func([TradeId, IDL.Float64], [], []),
  'deposit' : IDL.Func([IDL.Float64], [], []),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClosedTrades' : IDL.Func([], [IDL.Vec(ClosedTrade)], ['query']),
  'getOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
  'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeTrade' : IDL.Func(
      [IDL.Text, TradeSide, IDL.Float64, IDL.Float64],
      [TradeId],
      [],
    ),
  'resetAccount' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'withdraw' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TradeId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const TradeSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const ClosedTrade = IDL.Record({
    'id' : TradeId,
    'pnl' : IDL.Float64,
    'closeTimestamp' : Time,
    'pair' : IDL.Text,
    'side' : TradeSide,
    'closePrice' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'openTimestamp' : Time,
    'lotSize' : IDL.Float64,
  });
  const Position = IDL.Record({
    'id' : TradeId,
    'pair' : IDL.Text,
    'side' : TradeSide,
    'entryPrice' : IDL.Float64,
    'openTimestamp' : Time,
    'lotSize' : IDL.Float64,
  });
  const TransactionId = IDL.Nat;
  const TransactionType = IDL.Variant({
    'withdraw' : IDL.Null,
    'deposit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : TransactionId,
    'transactionType' : TransactionType,
    'timestamp' : Time,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'closeTrade' : IDL.Func([TradeId, IDL.Float64], [], []),
    'deposit' : IDL.Func([IDL.Float64], [], []),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClosedTrades' : IDL.Func([], [IDL.Vec(ClosedTrade)], ['query']),
    'getOpenPositions' : IDL.Func([], [IDL.Vec(Position)], ['query']),
    'getTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeTrade' : IDL.Func(
        [IDL.Text, TradeSide, IDL.Float64, IDL.Float64],
        [TradeId],
        [],
      ),
    'resetAccount' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'withdraw' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };